#!/usr/bin/env bash
set -eu

function download-data {
  remove-data
  local path=/var/lib/machines/ocitysmap/var/tmp/data$(get-extension "$1")
  if command -v curl > /dev/null; then
    sudo curl -L -o "$path"~ "$1"
  elif command -v wget > /dev/null; then
    sudo wget -O "$path"~ "$1"
  fi
  sudo mv "$path"{~,}
}

function get-extension {
  local filename=${1##*/}
  [[ $filename != *.* ]] || echo ".${filename#*.}"
}

function import-data {
  sudo systemd-nspawn -q -M ocitysmap bash -eu"$-" << EOF
  /etc/init.d/postgresql start || /etc/init.d/postgresql start
  echo maposmatic | osm2pgsql -Wck -H localhost -U maposmatic -d maposmatic /var/tmp/data* $@
EOF
}

function main {
  local url=${1?A URL is required.}
  shift
  download-data "$url"
  import-data "$@"
  remove-data
}

function remove-data {
  sudo sh -c 'rm -f /var/lib/machines/ocitysmap/var/tmp/data*'
}

main "$@"
