#!/usr/bin/env bash
set -eu

function copy-output {
  mkdir -p ~/Downloads
  sudo cp /var/lib/machines/ocitysmap/root/ocitysmap/citymap.pdf ~/Downloads/map.pdf
  sudo chown "$USER": ~/Downloads/map.pdf
  echo 'Output: ~/Downloads/map.pdf'
}

function main {
  render-map "${@?An argument is required.}"
  copy-output
}

function render-map {
  sudo systemd-nspawn -q -M ocitysmap --chdir=/root/ocitysmap bash -eu"$-" -c '
  /etc/init.d/postgresql start
  if [[ $# == 1 && $1 != -* ]]; then
    set -- -t "$1" --osmid="$(sudo -i -u postgres psql -A -c "SELECT osm_id FROM planet_osm_polygon WHERE name ILIKE '\''%$1%'\'' LIMIT 1" -d maposmatic | sed -n '2p')"
  fi
  ./render.py -l multi_page --paper-format="Din A5" "$@"
  ' -- "$@"
}

main "$@"
