#!/usr/bin/env bash
set -eu

function bootstrap-container {
  install-packages debian-archive-keyring debootstrap
  if ! sudo ls /var/lib/machines/ocitysmap &> /dev/null; then
    if ! sudo debootstrap stretch /var/lib/machines/ocitysmap; then
      sudo rm -fr /var/lib/machines/ocitysmap
      return 1
    fi
  fi
}

function clone-ocitysmap {
  sudo ls /var/lib/machines/ocitysmap/root/ocitysmap &> /dev/null || sudo git -C /var/lib/machines/ocitysmap/root clone --depth=1 https://github.com/hholzgra/ocitysmap.git
}

function configure-autologin {
  sudo mkdir -p /var/lib/machines/ocitysmap/etc/systemd/system/console-getty.service.d
  sudo tee /var/lib/machines/ocitysmap/etc/systemd/system/console-getty.service.d/override.conf > /dev/null << \EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin=root console $TERM
EOF
}

function install-container-packages {
  sudo systemd-nspawn -M ocitysmap bash -l -c 'dpkg -s "$@" &> /dev/null || apt install -y "$@"' -- "$@"
}

function install-packages {
  ! command -v dpkg > /dev/null || dpkg -s "$@" &> /dev/null || sudo apt install -y "$@"
  ! command -v pacman > /dev/null || pacman -Q "$@" &> /dev/null || sudo pacman -Sy --needed --noconfirm "$@"
}

function main {
  bootstrap-container
  setup-container
  clone-ocitysmap
  setup-postgresql
}

function setup-container {
  configure-autologin
  configure-hosts
  update-apt-cache
}

function setup-postgresql {
  install-container-packages postgis postgresql postgresql-contrib sudo
  sudo systemd-nspawn -M ocitysmap bash -eu"$-" << \EOF
  /etc/init.d/postgresql start
  sudo -u postgres psql -c '\du' | grep -q ' maposmatic ' || sudo -u postgres createuser maposmatic
  sudo -u postgres psql -c '\l' | grep -q ' maposmatic ' || sudo -u postgres createdb -O maposmatic maposmatic
EOF
}

function configure-hosts {
  sudo sed -i 's/\tlocalhost$/\0 ocitysmap/' /var/lib/machines/ocitysmap/etc/hosts
}

function update-apt-cache {
  sudo ls /var/lib/machines/ocitysmap/var/cache/apt/pkgcache.bin &> /dev/null || sudo systemd-nspawn -M ocitysmap apt update
}

main "$@"
