#!/usr/bin/env bash
set -eu

function main {
  sudo systemd-nspawn -q -M ocitysmap bash -eu"$-" << \EOF
  /etc/init.d/postgresql start
  for name in planet_osm_{line,point,polygon,roads}; do
    sudo -u postgres psql -c "UPDATE $name SET name = tags->'name:en' WHERE tags->'name:en' IS NOT NULL" -d maposmatic
  done
EOF
}

main "$@"
